### ISSUE TITLE
Conversation bugs/requests

### ISSUE THREAD

**Issue by RidiculousPony** [RidiculousPony/DateBuilder#52]
- [x] Back button is present on Deck Select screen when sent there directly (letting you break from the flow)
- [x] Back button is present on Location Select screen when sent there directly.
- [x] Add a blinking cursor (triangle?) at the end of each StoryText to indicate to player they click to advance.
- [x] Leave date button goes to old date fail screen instead of going to where SetFullDate set. (should it count as a loss? or should we just remove this button?)
- [x] Add a button (left key?) to go back one StoryText.
- [ ] Make back button able to even go back to previous node.
- [ ] When going back to a previous Response node, disable the options you didn't choose.
- [x] Add a way to put a name over dialog from a specific character (a la Katawa)

**Comment by Caydo** [comment]
* Adding "Speaker" : "CharacterName" to the top of a trigger now shows that name above the storyline text.

**Comment by Caydo** [comment]
We might want to turn the Leave Date button into an options button (for saving/loading, etc.?) I don't know if we really want the player to be able to just outright leave, unless the story allows it? It seems like it's more of a button to exit the application now?

**Comment by Caydo** [comment]
Removed Back button from Deck Select since the player should only ever get there after location select and/or location's been set by conversation and they have unlocked cards.

**Comment by Caydo** [comment]
Removed Back button from Location Select too. Since we only ever really want the player to go forward unless they're in save/load then those buttons don't really need to exist.

**Comment by Caydo** [comment]
Removed the Leave Date (concede) button and dialog. Winning and losing kicks you to the win/lose scenes currently if you run through the Saber conversation stuff. But, we probably want to change those to be strikes/good end/bad end/more conversation instead (easy switch of node ID.)

It seems like we might want a more global options button for during different spots of gameplay to exit, save, etc. Though we'll need to figure out if we want to limit saving, what we need to definitely save (obviously we've got some stuff in save file already.)

**Comment by Caydo** [comment]
Is there a limit to how far back you can traverse through nodes? Do we want there to be? Currently we only remember the current trigger and just keep shoving forward without any real consideration for the past. Though that shouldn't be too hard to put in...I think?

**Comment by Caydo** [comment]
Left arrow key back tracks one story text string param per press. It backtracks as far as it can 'til it's at the start of the node. To hop back to another story node i'll need to add remembering previous nodes.

To change what input the backtrack is on go to Edit > Project Settings > Input, then set Positive Button to something other than "left". We might need to research what the other buttons are if we want to change it.

**Comment by Caydo** [comment]
I can't think of anything other than decisions where we wouldn't want the blinking "you can click to advance" icon. So, maybe the require response triggers should turn it off otherwise whatever it is will pretty much always be visible? (well also hide it during card unlocks.)

**Comment by Caydo** [comment]
Added fading in/out flower (placeholder) to bottom right of storyline text area. It's controlled by the current trigger's parameter of "DisplayAdvanceIndicator". This can be optionally added and is set to 0 (false) or 1 (true) on whether to have it display/animate. If a trigger doesn't have the parameter, it defaults to false.

**Comment by Caydo** [comment]
Removed the back to main menu button.

**Comment by Caydo** [comment]
Going to close this out since everything but the node traversal system's in which I consolidated to https://github.com/RidiculousPony/DateBuilder/issues/53.
